Properties
cfu.iniziali=20
borsa.peso.max=10
attrezzo.speciale.stanza.bloccata=chiave
attrezzo.speciale.stanza.buia=lanterna
soglia.magica.stanza.magica=3
messaggio.dono.mago=Sei un vero simpaticone,con una mia magica azione, troverai un nuovo oggetto per il tuo borsone!
messaggio.scuse.mago=Mi spiace, ma non ho piu' nulla...
messaggio.permaloso.strega=Non mi hai salutato!!... sei stato spostato in una stanza con meno attrezzi...
messaggio.buono.strega=Sei stato spostato in una stanza con piu attrezzi.
cibo.preferito.cane=croccantini
messaggio.interazione.cane=Woof Woof!! ops il cane di ha morso -1 CFU
